#!/bin/bash
echo "=== Identifiers ==="
echo "== Process ID and Parent Process ID =="
echo "PID: `awk '/^Pid/{print $2}' /proc/$1/status`, PPID: `awk '/^PPid/{print $2}' /proc/$1/status`"
echo "== Effective User and Group ID =="
echo "EUID: `awk '/^Uid/{print $3}' /proc/$1/status`, EGID: `awk '/^Gid/{print $3}' /proc/$1/status`"
echo "== Real User and Group ID =="
echo "RUID: `awk '/^Uid/{print $2}' /proc/$1/status`, RGID: `awk '/^Gid/{print $2}' /proc/$1/status`"
echo "== File System User and Group ID =="
echo "FSUID: `awk '/^Uid/{print $5}' /proc/$1/status`, FSGID: `awk '/^Gid/{print $5}' /proc/$1/status`"
